apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "remnanode.fullname" . }}-downloader-script
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-5"
data:
  download.sh: |
    #!/bin/sh
    set -e
    DEST_DIR="/data"
    mkdir -p $DEST_DIR
    download_file() {
        local url=$1
        local file=$2
        local dest="$DEST_DIR/$file"
        echo "[STEP] Downloading $file..."
        if curl -sSL --connect-timeout 15 --max-time 300 --retry 3 -o "$dest.tmp" "$url"; then
            mv "$dest.tmp" "$dest"
            chmod 644 "$dest"
            echo "[OK] $file updated."
        else
            echo "[ERROR] Failed to download $file"
            exit 1
        fi
    }
    download_file "https://github.com/kutovoys/ru_gov_zapret/releases/latest/download/zapret.dat" "zapret.dat"
    download_file "https://raw.githubusercontent.com/runetfreedom/russia-v2ray-rules-dat/release/geoip.dat" "geoip.dat"
    download_file "https://raw.githubusercontent.com/runetfreedom/russia-v2ray-rules-dat/release/geosite.dat" "geosite.dat"