{{- if .Values.autoUpdate.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "remnanode.fullname" . }}-daily-update
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.autoUpdate.schedule | quote }}
  concurrencyPolicy: Forbid # Prevent concurrent executions of the job
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: cronjob
        spec:
          # Bind the service account ONLY to the CronJob
          serviceAccountName: {{ include "remnanode.fullname" . }}-updater
          containers:
          - name: kubectl
            image: "{{ .Values.autoUpdate.image.repository }}:{{ .Values.autoUpdate.image.tag }}"
            imagePullPolicy: {{ .Values.autoUpdate.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - kubectl rollout restart deployment/{{ include "remnanode.fullname" . }}
          restartPolicy: OnFailure
{{- end }}