apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "remnanode.fullname" . }}
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "remnanode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "remnanode.selectorLabels" . | nindent 8 }}
      {{- if not .Values.node.existingSecret }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
    spec:
      automountServiceAccountToken: false
      
      hostNetwork: {{ .Values.node.hostNetwork | default false }}
      dnsPolicy: {{ if .Values.node.hostNetwork }}ClusterFirstWithHostNet{{ else }}ClusterFirst{{ end }}

      containers:
        - name: remnanode
          image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag }}"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: NODE_PORT
              value: {{ .Values.node.apiPort | quote }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ coalesce .Values.node.existingSecret (printf "%s-secrets" (include "remnanode.fullname" .)) }}
                  key: SECRET_KEY
            - name: XRAY_LOCATION_ASSET
              value: /usr/local/bin
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.node.apiPort }}
              name: api
              protocol: TCP
              hostPort: {{ .Values.node.apiPort }}

            {{- range .Values.inbounds }}
            - containerPort: {{ .port }}
              name: tcp-{{ .port }}
              protocol: TCP
              {{- if eq .mode "direct" }}
              hostPort: {{ .port }}
              {{- end }}

            {{- if eq .mode "direct" }}
            - containerPort: {{ .port }}
              name: udp-{{ .port }}
              protocol: UDP
              hostPort: {{ .port }}
            {{- end }}
            {{- end }}

          volumeMounts:
            - name: xray-data-cache
              mountPath: /usr/local/bin/geoip.dat
              subPath: geoip.dat
            - name: xray-data-cache
              mountPath: /usr/local/bin/geosite.dat
              subPath: geosite.dat
            - name: xray-data-cache
              mountPath: /usr/local/bin/zapret.dat
              subPath: zapret.dat

      volumes:
      - name: xray-data-cache
        hostPath:
          path: {{ printf "%s/%s-data" .Values.node.dataDir (include "remnanode.fullname" .) }}
          type: DirectoryOrCreate