apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "remnanode.fullname" . }}-sync-geo
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-2"
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: downloader
        image: curlimages/curl:8.18.0
        command: ["/bin/sh", "/scripts/download.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: storage
          mountPath: /data
      restartPolicy: OnFailure
      volumes:
      - name: scripts
        configMap:
          name: {{ include "remnanode.fullname" . }}-downloader-script
      - name: storage
        persistentVolumeClaim:
          claimName: {{ include "remnanode.fullname" . }}-geodata