apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "remnanode.fullname" . }}-geodata
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-2"
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.node.geodata.storageClassName }}
  storageClassName: {{ .Values.node.geodata.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.node.geodata.size | default "512Mi" }}