# charts/remnanode/templates/rbac.yaml
{{- if .Values.autoUpdate.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "remnanode.fullname" . }}-updater
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "remnanode.fullname" . }}-restarter
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "remnanode.fullname" . }}-restarter-binding
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "remnanode.fullname" . }}-updater
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "remnanode.fullname" . }}-restarter
  apiGroup: rbac.authorization.k8s.io
{{- end }}