apiVersion: v1
kind: Service
metadata:
  name: {{ include "remnanode.fullname" . }}
  labels:
    {{- include "remnanode.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "remnanode.selectorLabels" . | nindent 4 }}
  ports:
    # Expose ports for all Ingress-based modes (SNI, Path, gRPC, XHTTP)
    {{- range .Values.inbounds }}
    {{- if ne .mode "direct" }}
    - port: {{ .port }}
      name: {{ .name }}
      targetPort: {{ .port }}
    {{- end }}
    {{- end }}website-service.yaml